### PR TITLE
use detachLeash to track when lead detaches

### PR DESCRIPTION
**Pull request by Enriath**
I was quite disappointed to find this mod not working on servers, so I made it work on servers as a clientside mod.

This is done by listening in to when the client detaches the lead itself. There are 5 uses of this specific to MobEntity, but from my testing on Allays this has been very consistent. This also means that there don't need to be messy checks based on distance.

This has been tested:
- 🔔 When the lead breaks (the main situation you'd want to know)
- 🔕 When you purposefully remove the lead from a mob
- 🔔 When a mob enters a boat (this does still notify you, as you'd want to go pick up your lead)
- 🔕 When you attach the lead to a fence
- 🔔 When the mob dies
- 🔔 When you die

This has also been tested with another player, to confirm that the mod only triggers from leads you are holding onto.

### CODE REVIEW

**Comment by Superkat32** [comment]
Wow! This seems great! I really wanted to add server support but I couldn't get it working. I'll test out the new changes once I get IntelliJ working because it(or something) is giving me some issues right now.

My biggest question, however, is how? How did you manage to get it working? Was it through trial and error? Was it with educated guesses? Or something else I'm not thinking of?

**Comment by Enriath** [comment]
While I was still figuring out how to set up Fabric and viewing sources, I found some Forge docs from 1.16 that showed there was a load of specific vars and functions relating to leads. After getting IJ set up, I confirmed it was still in the 1.19 source. Then it was just a matter of figuring out how Fabric does mixins specifically (I have experience with a similar system from another project), and figuring out what called the function when (it was mostly setting the holding entity id).

**Comment by Superkat32** [comment]
Hello! Sorry for the delay but I have started and finished testing the mod myself on multiplayer(1.19.2, I'll probably be updating the mod to 1.19.3 sometime next year) and it works wonderfully! I plan on merging the request, but I have one more question before doing so. Do you want credit? If so, how and where do you want to be credited? From what I can tell, GitHub should automatically credit you in the repo. However, I'm also willing to give credit in both the Modrinth page and the GitHub README(It would probably be a line of text that says something along the lines of, "Big thanks to Enriath for making the mod work in multiplayer!" A link could also be added, e.g. "You can find her here: _insert a link here_.") I'm not really sure how crediting works with pull requests, so my apologies if this question is a really silly one, but I want to make sure I credit properly.

**Comment by Superkat32** [comment]
> Hello! Sorry for the delay but I have started and finished testing the mod myself on multiplayer(1.19.2, I'll probably be updating the mod to 1.19.3 sometime next year) and it works wonderfully! I plan on merging the request, but I have one more question before doing so. Do you want credit? If so, how and where do you want to be credited? From what I can tell, GitHub should automatically credit you in the repo. However, I'm also willing to give credit in both the Modrinth page and the GitHub README(It would probably be a line of text that says something along the lines of, "Big thanks to Enriath for making the mod work in multiplayer!" A link could also be added, e.g. "You can find her here: _insert a link here_.") I'm not really sure how crediting works with pull requests, so my apologies if this question is a really silly one, but I want to make sure I credit properly.

Update on places I'm willing to add credit: I just remembered there is a credit section within the mod's code(the fabric.mod.json file.) I can also add credit there if you want it. (And if there is somewhere else where you want me to add credit that I'm not thinking of, let me know please!)

**Comment by Enriath** [comment]
I meant to reply to this earlier, but forgor :skull:
Overall, I don't really mind too much. Can credit me how you'd want to be credited :+1:

**Comment by Superkat32** [comment]
Alright! I'll merge it soon™! (probably within next few days)
Again, thank you so much for doing this! I had such a big smile whenever it worked on multiplayer! 

> but forgor 💀

xD

**Comment by Superkat32** [comment]
Merged! I've added credit in the code via a couple of comments, in the README.md, and will add credit to the Modrinth page once I update it there.
Thank you for doing this!

**Pull request merged**
